# Generated by Django 4.1.2 on 2022-10-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_intervalos_genrespotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalos',
            name='genrePai',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
