# Generated by Django 4.1.2 on 2022-10-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_intervalos_genrepai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalos',
            name='genrePai',
        ),
    ]
