# Generated by Django 4.1.2 on 2022-10-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_intervalos_genrepai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalos',
            name='genreSpotify',
        ),
    ]
