# Generated by Django 4.1.2 on 2022-11-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_intervalos_genrespotify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMusic', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('artista', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('evaluation', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
