# Generated by Django 4.1.2 on 2022-11-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_artistas_nomeartista'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacoes',
            name='nomeArtista',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
