# Generated by Django 4.1.2 on 2022-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_avaliacoes_nomeartista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
